exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: "frappe_ip_ban.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: ["--fix"]
        name: "Python linter"

      - id: ruff
        args: ["--select=T20","--exit-zero"]
        name: "Print Statement Warning"
        stages: [pre-commit]

      - id: ruff-format
        name: "Python formatter"

  - repo: local
    hooks:
      - id: clone-local-repo
        name: clone-local-repo
        entry: bash -c 'TARGET_DIR=".frappe-semgrep" && [ ! -d "$TARGET_DIR" ] && git clone "https://github.com/frappe/semgrep-rules" "$TARGET_DIR" || true'
        language: system
        always_run: true

  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.91.0'
    hooks:
      - id: semgrep-ci
        name: "Sempgrep: frappe"
        args: ['--config', './.frappe-semgrep/rules', '--config','r/python.lang.correctness','--error', '--skip-unknown-extensions', '--metrics','off']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: "JS/TS Formatter"
        language: node
        files: ^.*\.(jsx|tsx|ts|js)$
        types: [file]
        exclude: |
            (?x)^(
                frappe_ip_ban/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                frappe_ip_ban/templates/includes/.*|
                frappe_ip_ban/public/js/lib/.*
            )$

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false